# Generated by Django 5.0.6 on 2026-05-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название культуры')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Код культуры')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название болезни')),
                ('symptoms', models.JSONField(default=list, help_text='Список ключей симптомов: yellowing, dark_spots, deformation, …', verbose_name='Симптомы')),
                ('symptom_labels', models.JSONField(default=list, help_text='Читаемые названия симптомов на русском', verbose_name='Метки симптомов (для отображения)')),
                ('recommendations', models.JSONField(default=list, verbose_name='Рекомендации')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Умеренная'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Уровень угрозы')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='diagnosis.crop', verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
                'ordering': ['crop', 'name'],
            },
        ),
    ]
